from pathlib import Path

import pandas as pd


# Input and output locations
INPUT = Path("data/analysis/top500-2026-10-04/observations.csv")
OUTPUT = Path("data/analysis/signal_reference_table.tsv")


def main() -> None:
    # Read the observations generated by the scanner
    observations = pd.read_csv(INPUT)

    # Keep each signal only once, even though it appears for many domains
    signals = (
        observations[["signal"]]
        .drop_duplicates()
        .sort_values("signal")
        .reset_index(drop=True)
    )

    signals.insert(0, "No.", range(1, len(signals) + 1))

    signals.insert(
        1,
        "Group",
        signals["signal"].str.split(".").str[0].str.title(),
    )

        # Add blank columns for your research notes
    signals["Possible errors"] = ""
    signals["Possible reason for error"] = ""
    signals["Interpretation"] = ""
    signals["Why the signal matters"] = ""

    # Arrange the columns in the order requested
    table = signals[
        [
            "No.",
            "Group",
            "signal",
            "Possible errors",
            "Possible reason for error",
            "Interpretation",
            "Why the signal matters",
        ]
    ]

    # Write a tab-separated file that can be copied into Google Docs or Sheets
    table.to_csv(OUTPUT, sep="\t", index=False)

    print(f"Created: {OUTPUT}")
    print(f"Number of unique signals: {len(table)}")


if __name__ == "__main__":
    main()